language: python
python:
    - "3.6"
    - "3.7"

install:
    - pip install --upgrade pip
    - pip install tensorflow
    - pip install h5py
    - pip install -e .

script:
    - python -m unittest discover -s tests/ -v

